<a href="https://colab.research.google.com/github/PerfectMach1ne/machine-learning-data-science/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy time
Based on https://www.youtube.com/watch?v=QUT1VHiLmmI
Might expand it with own research sometime later (unless I decide to do it in a different Jupyter Notebook or within separate Python scripts).

---



In [107]:
import numpy as np

In [108]:
a = np.array([5,7,4,9])
b = np.array([[0,1,0],[1,0,1],[0,1,1]], dtype='int16')
print(a)
print(b)

[5 7 4 9]
[[0 1 0]
 [1 0 1]
 [0 1 1]]


In [109]:
# Get dimension
print(a.ndim)
print(b.ndim)

1
2


In [110]:
# Get shape
print(a.shape)
print(b.shape)

(4,)
(3, 3)


In [111]:
# Get type
print(a.dtype)
print(b.dtype)

int64
int16


In [112]:
# Get size
print(a.itemsize)
print(b.itemsize)
c = np.array([1,2,3], dtype='int8')
print(c.itemsize)
# Get total size
print(b.size * b.itemsize)
print(b.nbytes) # number of bytes

8
2
1
18
18


## Accessing/changing specific elements, rows, columns, etc

In [113]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
print(a.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)


In [114]:
# Get a specific element [r, c]
a[1,5]

13

In [115]:
# Get a specific row
print(a[0, :])
# Get a specific column
print(a[:, 2])

[1 2 3 4 5 6 7]
[ 3 10]


In [116]:
# [startindex:endindex:stepsize]
a[0,1:-1:2]

array([2, 4, 6])

In [117]:
print(a)
a[1,5] = 57
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 57 14]]


In [118]:
print(a)
a[:,4] = [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 57 14]]
[[ 1  2  3  4  1  6  7]
 [ 8  9 10 11  2 57 14]]


#### 3D example

In [119]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [120]:
print(b[0,1,:])
print(b[1,:,:])
print(b[1,1,0])

[3 4]
[[5 6]
 [7 8]]
7


#### Initializing different types of arrays

In [121]:
# All 0s matrix

In [122]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [123]:
# All 1s matrix
np.ones((5,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [124]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [125]:
# Any other number
np.full((2,2), 57)

array([[57, 57],
       [57, 57]])

In [126]:
np.full_like(c.shape, 4)

array([4])

In [127]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.60308314, 0.72239381],
       [0.78213407, 0.68290738],
       [0.99545251, 0.59186701],
       [0.1417175 , 0.30078643]])

In [128]:
# Random integer values
np.random.randint(-7,5,size=(3,3))

array([[-4, -1,  2],
       [ 4,  0,  0],
       [-3,  3, -3]])

In [129]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [130]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


#### Special thingy

In [131]:
output = np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [132]:
z = np.zeros((3,3))
z[1,1] = 0
print(z)
output[1:-1,1:-1] = z # could also be [1:4, 1:4] but I just figured out with my poorly functioning brain that there is a more general way of doing it
print(output)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [133]:
w = np.zeros((3,3))
w[1,1] = 9
output[1:-1,1:-1] = w
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


***Dangerous thiiing***

In [134]:
a = np.array([1,2,3])
b = a # point to the same thing as a
b[0] = 100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [135]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


#### M a f f

In [136]:
# Element-wise arithmetic
a = np.array([1,2,3,4])
a += 2
print(a)
a -= 2
print(a)
a *= 2
print(a)
b = a / 4
print(b)
a = a ** 2
print(a)
c = [-1,-2,-3,-4]
print(a + c)

[3 4 5 6]
[1 2 3 4]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 4 16 36 64]
[ 3 14 33 60]


In [137]:
np.cos(c)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

#### Linear algebruh

In [138]:
a = np.ones((2,8))
b = np.full((8,2), 2)
print(a)
print(b)
# a*b # won't work lol
c = np.matmul(a,b)
print(c)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]]
[[16. 16.]
 [16. 16.]]


#### "STATITSTICs"

In [139]:
stits = np.array([[1,2,3],[4,5,6]])
stits

array([[1, 2, 3],
       [4, 5, 6]])

In [140]:
np.min(stits)

1

In [141]:
np.min(stits, axis=1)

array([1, 4])

In [142]:
np.max(stits, axis=0)

array([4, 5, 6])

In [143]:
np.sum(stits)

21

#### Reorganizing arrays

In [144]:
before =  np.array([[1,2,3,4],[5,6,7,8]])
print(before)
# turning it into an 8 by 1
after = before.reshape((8,1))
print(after)
after = before.reshape((2,2,2))
print(after)
# Product of dimensions must equal to the number of all elements

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [145]:
# Vertical stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [146]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack([h1,h2]) # can be [h1,h2] or (h1,h2)

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

#### misc

In [ ]:
# load data from file without pandas
filedata = np.genfromtxt('data.txt', delimiter=';') # gets ; separated data from a data.txt file
# it'll automatically cast it to float, unless:
filedata = filedata.astype('int32')

There is a thing called boolean masking.
`filedata > 50`

and you can also take the values greater than 50 into a new array: `filedata[filedata > 50]`

And you can index with a list in NumPy:

In [148]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [ ]:
((filedata > 50) & (filedata < 100))